=== AnaCR22/sew/xml/circuito.dtd
<!ELEMENT circuito (dimensiones, carrera, patrocinador, referencias, fotos, videos, puntoOrigen, tramos, vencedor, clasificacion)>
<!ATTLIST circuito 
  nombre CDATA #REQUIRED
  localidad CDATA #REQUIRED
  pais CDATA #REQUIRED
>

<!ELEMENT dimensiones (#PCDATA)>
<!ATTLIST dimensiones 
    longitud CDATA #REQUIRED
    anchura CDATA #REQUIRED
    unidad CDATA #REQUIRED
>

<!ELEMENT patrocinador (#PCDATA)>

<!ELEMENT carrera EMPTY>
<!ATTLIST carrera 
  fecha CDATA #REQUIRED
  horaInicio CDATA #REQUIRED
  vueltas CDATA #REQUIRED
>

<!ELEMENT referencias (referencia, referencia, referencia, referencia*)>
<!ELEMENT referencia EMPTY>
<!ATTLIST referencia url CDATA #REQUIRED>

<!ELEMENT fotos (foto | (foto, foto) | (foto, foto, foto) | (foto, foto, foto, foto) | (foto, foto, foto, foto, foto))>
<!ELEMENT foto EMPTY>
<!ATTLIST foto archivo CDATA #REQUIRED>

<!ELEMENT videos (video | (video, video) | (video, video, video) | (video, video, video, video) | (video, video, video, video, video))>
<!ELEMENT video EMPTY>
<!ATTLIST video archivo CDATA #REQUIRED>

<!ELEMENT punto EMPTY>
<!ATTLIST punto 
  longitud CDATA #REQUIRED
  latitud CDATA #REQUIRED
  altitud CDATA #REQUIRED
>

<!ELEMENT puntoOrigen (punto)>


<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (punto)>
<!ATTLIST tramo 
  distancia CDATA #REQUIRED
  sector CDATA #REQUIRED
>

<!ELEMENT vencedor EMPTY>
<!ATTLIST vencedor 
  nombre CDATA #REQUIRED
  tiempo CDATA #REQUIRED
>

<!ELEMENT clasificacion (clasificado, clasificado, clasificado)>
<!ELEMENT clasificado EMPTY>
<!ATTLIST clasificado 
  nombre CDATA #REQUIRED
  puntos CDATA #REQUIRED
>

=== AnaCR22/sew/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito nombre="Circuito de Jerez – Ángel Nieto" localidad="Jerez de la Frontera" pais="España">

    <dimensiones longitud="4428" anchura="12" unidad="m"/>
    
    <carrera fecha="2025-04-27" horaInicio="14:00" vueltas="25" />

    <patrocinador>Red Bull</patrocinador>

    <referencias>
        <referencia url="https://www.circuitodejerez.com" />
        <referencia url="https://es.wikipedia.org/wiki/Circuito_de_Jerez" />
        <referencia url="https://www.motogp.com/es/circuito/Jerez" />
    </referencias>
    
    <fotos>
        <foto archivo="Jerez_Panorama.jpg" />
    </fotos>

    <videos>
        <video archivo="Jerez_Onboard.mp4" />
        <video archivo="Jerez_Highlights.mp4" />
    </videos>

    <puntoOrigen>
        <punto longitud="-6.0344" latitud="36.7089" altitud="58" />
    </puntoOrigen>

    <tramos>
        <tramo distancia="600" sector="1">
            <punto longitud="-6.0341" latitud="36.7095" altitud="60" />
        </tramo>
    </tramos>

    <vencedor nombre="Pedro Acosta" tiempo="41:37.812" />

    <clasificacion>
        <clasificado nombre="Pedro Acosta" puntos="270" />
        <clasificado nombre="Francesco Bagnaia" puntos="260" />
        <clasificado nombre="Marc Márquez" puntos="254" />
    </clasificacion>
    
</circuito>
